// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhjdhpxlhxjamhbsplfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoamRocHhsaHhqYW1oYnNwbGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTU5MjgsImV4cCI6MjA2OTk5MTkyOH0.BiwCxE4Qkovrt23dY1446erHTzqJTkVIbAYw2eC4A-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});